### ISSUE TITLE
Performance in the indoor environment.

### ISSUE THREAD

**Issue by mxa1097** [irapkaist/SC-LeGO-LOAM#10]
Hello, thank you for sharing your work. I used the code using VLP-16 without IMU in the indoor environment. I cannot get really good mapping result using the parameters by default. Could you please give me some suggestions? Thanks.

**Comment by kissb2** [comment]
Thank you for a good question. 
I think that your question is actually important and could be helpful later to other guys working in indoor env. 

Actually the current code and parameters are optimal to work in an outdoor environment. 
so my guide to use this system for the indoor, vlp16 lidar is below:

1. Use the smaller radius 
- i.e., see here https://github.com/irapkaist/SC-LeGO-LOAM/blob/master/SC-LeGO-LOAM/LeGO-LOAM/include/Scancontext.h#L81
- Currently, the parameter used 80m, which is adequate for outdoor.  But I think to use the smaller value for indoor env (because indoor is usually narrow than outdoor)
- I haven't tested what the exact value is suitble for indoor env, but I guess 30-50m is feasible.  

2. Use the smaller threshold
- See here https://github.com/irapkaist/SC-LeGO-LOAM/blob/3170ba1de7bb0d3f8de5192742e0bbe267415ab4/SC-LeGO-LOAM/LeGO-LOAM/include/Scancontext.h#L92
- Our slam system is currently using a robust back-end (e.g., caucy kernal or DCS) so the threshold is set quite large value. But I think using smaller value of it (i.e., more conservative and cuase less false loop factors) would help work in an indoor env. 

3. Contain same-direction-revisit with enough length 
- Our slam system's current version well works under where enough length of revisits (e.g, see MulRan dataset's trajectory https://sites.google.com/view/mulran-pr/dataset) exist. 
- I think 10-20m would be okay. The more revisit, the better the loop closing performance and final map quality.

**Comment by mxa1097** [comment]
Thank you for your reply! It is really helpful.

**Comment by Srichitra-S** [comment]
Hi,
Did the above mentioned changes have any affect on the generated map? 
I tried changing the parameters but did not see any notable difference in the map generated.
