### ISSUE TITLE
There is no imu data in MulRan dataset?

### ISSUE THREAD

**Issue by jacksparal** [irapkaist/SC-LeGO-LOAM#11]
There is no imu data in MulRan dataset? 
In the file_player_mulran,it says imu data is in 'xsens_imu.csv',but i can't find it.
Is your result without imu ?

**Comment by gisbi-kim** [comment]
The xsens IMU data is officially unpublished through our ICRA20 dataset paper 
(because MulRan dataset particularly aimed the place recognition research)

so I marked as false the IMU publishing section in the file_player_mulran, here
https://github.com/irapkaist/file_player_mulran/blob/e1bb058f844d6beaba262fafa65d8a0df54500a1/src/ROSThread.cpp#L16

but if you need the IMU data for your application, 
I have the raw data (i.e., xsens_imu.csv) so please send me a mail (paulgkim@kaist.ac.kr)

thank you.

**Comment by gisbi-kim** [comment]
IMU and (Ublox, commercial level) GPS data for all sequences are officially released!

please refer https://github.com/irapkaist/file_player_mulran
and the dataset page https://sites.google.com/view/mulran-pr/home
