### ISSUE TITLE
How to use the Complex Urban dataset to build the map, and what parameters need to be modified？

### ISSUE THREAD

**Issue by 0ontheroad** [irapkaist/SC-LeGO-LOAM#15]
How to use the Complex Urban dataset to build the map, and what parameters need to be modified？
and the address of this dataset is https://irap.kaist.ac.kr/dataset/index.html, thank you!!

**Comment by gisbi-kim** [comment]
You first change the topic name here 
https://github.com/irapkaist/SC-LeGO-LOAM/blob/705367eceaef797d9b4bda1c5bb91c9a0ec771f7/SC-LeGO-LOAM/LeGO-LOAM/include/utility.h#L57

and then comment this part 
https://github.com/irapkaist/SC-LeGO-LOAM/blob/705367eceaef797d9b4bda1c5bb91c9a0ec771f7/SC-LeGO-LOAM/LeGO-LOAM/include/utility.h#L100

and uncomment this part because complex urban dataset used vlp16 lidar 
https://github.com/irapkaist/SC-LeGO-LOAM/blob/705367eceaef797d9b4bda1c5bb91c9a0ec771f7/SC-LeGO-LOAM/LeGO-LOAM/include/utility.h#L66

But one thing I concern is lego-loam algorithm is suitable for horizontally mounted lidars (because it used range image for feature selection, the range image shows best performance when it mounted horizontally) 

thank you.

**Comment by Maple-Yang-neu** [comment]
How to use the Complex Urban dataset to build the map? The KAIST dataset contains two LiDAR, and named /ns1/velodyne_points and /ns2/velodyne_points, but not /os1_points.
